CC = g++
CCFLAGS = -Wall -O0 -g 
RM = rm 

%.o : %.cpp
	$(CC) -c $(CCFLAGS) -o $@ $<

hello_world: hello_world.o
	$(CC) -o $@ $<
hello_world2: hello_world2.o
	$(CC) -o $@ $<
hello_world3: hello_world3.o
	$(CC) -o $@ $<
bmi: bmi.o
	$(CC) -o $@ $<
.PHONY: clean

clean:
	$(RM) *.o