CC = g++
CFLAGS = -g -Wall -o

myroot: myroot.cpp
	$(CC) $(CFLAGS) $@ $<
mypolynom: mypolynom.cpp
	$(CC) $(CFLAGS) $@ $<
mycomplex: mycomplex.cpp
	$(CC) $(CFLAGS) $@ $<

clean:
	rm *.o
clean_exe:
	ls | grep -v "\."|grep -v "MAKEFILE" | xargs rm